#!/sbin/busybox sh
#

XM=/res/xtreme;
BUSY=/sbin/busybox;
UCI_CONFIG=$XM/config.json;
UCI_ACTION=$XM/actions/;
DEBUG=$XM/debug;

if [ ! -f $UCI_CONFIG ]; then
	$BUSY mount -t rootfs -o rw,remount rootfs;
	$BUSY chmod -R 755 $UCI_ACTION;
	
	if [ ! -f $DEBUG/pvs_bin ]; then
		PVS=`$BUSY dmesg | $BUSY grep PVS`;
		$BUSY echo ${PVS##*:} > $DEBUG/pvs_bin;
	fi
	
	if [ ! -f $DEBUG/speed_bin ]; then
		SPEED=`$BUSY dmesg | $BUSY grep SPEED`;
		$BUSY echo ${SPEED##*:} > $DEBUG/speed_bin;
	fi
	
	if [ ! -f $DEBUG/last_kmsg ]; then
		LAST_KMSG=`$BUSY tail -n 1 /proc/last_kmsg`;
		$BUSY echo $LAST_KMSG > $DEBUG/last_kmsg;
	fi
	
	source $XM/config.json.generate > $UCI_CONFIG;
	
	$BUSY mount -t rootfs -o ro,remount rootfs;
fi;

case "${1}" in
  config)
		$BUSY cat $UCI_CONFIG;;
  configpath)
		$BUSY echo $UCI_CONFIG;;
  actionpath)
		$BUSY echo $UCI_ACTION;;
  reset)
		$BUSY mount -t rootfs -o rw,remount rootfs;
		$BUSY rm -f $UCI_CONFIG;
		$BUSY mount -t rootfs -o ro,remount rootfs;;
esac;
